== HTML5 For Mobile with Phonegap

Almost everyone has a smartphone in their pocket, or a tablet in their
bag these days. Development for the mobile web will allow the
developer to leverage much of their existing skills while providing
enough new features to keep things interesting.

With Phonegap it is possible to build cross platform native apps with
full access to the features of the phone such as the camera, the
accelerometer and GPS. 

However the mobile platform also has some challenges that are not
present on the conventional web, such as the fact that the mobile
application developer must be concerned with battery usage when
designing an application, which is not an issue when building
applications for conventional computers. 

This class will focus on the various mobile interfaces of Phongap as
well as how to use HTML5 most effectively.

Students should plan to bring a Tablet (IPad or Android). Students
wishing to develop for the IPad must have a mac.

NOTE: Knowledge of JavaScript, Web Development and basic use of Github
are required for this class.    

****
Class will be given in English
****   
 
